apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gltn7psej-go 
  janus-idp.io/tekton: gltn7psej-go
  backstage.io/kubernetes-id: gltn7psej-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gltn7psej-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml