apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gltn7psej-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gltn7psej-go 
  name: gltn7psej-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: gltn7psej-go 
